name: workflow_secrets
on: 
  workflow_dispatch:

env:
  DB_U: test
  DB_P: test

jobs:

  test-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: check env u
        run: echo "u=${{ env.DB_U }}"
      - name: check env p
        run: echo "p=${{ env.DB_P }}"