name: workflow_secrets
on: 
  workflow_dispatch:

env:
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:

  test-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: check env username
        run: echo "username=${{ env.DB_USERNAME }}"
      - name: check env password
        run: echo "password=${{ env.DB_PASSWORD }}"